// Regexes
// Remove commas from numbers:
// ([0-9]),([0-9]) -> \1\2
// Wrap data with immutable initialiser:
// ^([0-9]*) *([^0-9]*[^ 0-9]) *([0-9,]*) -> Map({ id: \1, name: '\2', continent: '', area: \3 }),
// NOTE: will have to tidy up area with decimal point and strings with 's in.

import { Map, List } from 'immutable';

export const continents = List([
  'North America',
  'South America',
  'Europe',
  'Africa',
  'Asia',
  'Australia',
  'Antarctica',
  'Ocean',
  'All'
]);

export const countries = List([
  Map({ id: 2, name: 'Pacific Ocean', continent: 'Ocean', area: 155557000 }),
  Map({ id: 3, name: 'Atlantic Ocean', continent: 'Ocean', area: 76762000 }),
  Map({ id: 4, name: 'Indian Ocean', continent: 'Ocean', area: 68556000 }),
  Map({ id: 5, name: 'Southern Ocean', continent: 'Ocean', area: 20327000 }),
  Map({ id: 6, name: 'Russia', continent: 'Europe', area: 17075200 }),
  Map({ id: 7, name: 'Arctic Ocean', continent: 'Ocean', area: 14056000 }),
  Map({ id: 8, name: 'Antarctica', continent: 'Antarctica', area: 14000000 }),
  Map({ id: 9, name: 'Canada', continent: 'North America', area: 9976140 }),
  Map({ id: 10, name: 'People\'s Republic of China', continent: 'Asia', area: 9706961 }),
  Map({ id: 11, name: 'United States', continent: 'North America', area: 9629091 }),
  Map({ id: 12, name: 'Brazil', continent: 'South America', area: 8511965 }),
  Map({ id: 13, name: 'Australia', continent: 'Australia', area: 7686850 }),
  Map({ id: 14, name: 'India', continent: 'Asia', area: 3287590 }),
  Map({ id: 15, name: 'Argentina', continent: 'South America', area: 2766890 }),
  Map({ id: 16, name: 'Kazakhstan', continent: 'Asia', area: 2717300 }),
  Map({ id: 17, name: 'Sudan', continent: 'Africa', area: 2505810 }),
  Map({ id: 18, name: 'Algeria', continent: 'Africa', area: 2381740 }),
  Map({ id: 19, name: 'Democratic Republic of the Congo', continent: 'Africa', area: 2345410 }),
  Map({ id: 20, name: 'Greenland', continent: 'North Amerca', area: 2166086 }),
  Map({ id: 21, name: 'Mexico', continent: 'South America', area: 1972550 }),
  Map({ id: 22, name: 'Saudi Arabia', continent: 'Asia', area: 1960582 }),
  Map({ id: 23, name: 'Indonesia', continent: 'Asia', area: 1919440 }),
  Map({ id: 24, name: 'Libya', continent: 'Asia', area: 1759540 }),
  Map({ id: 25, name: 'Iran', continent: 'Asia', area: 1648000 }),
  Map({ id: 26, name: 'Mongolia', continent: 'Asia', area: 1565000 }),
  Map({ id: 27, name: 'Peru', continent: 'South America', area: 1285220 }),
  Map({ id: 28, name: 'Chad', continent: 'Africa', area: 1284000 }),
  Map({ id: 29, name: 'Niger', continent: 'Africa', area: 1267000 }),
  Map({ id: 30, name: 'Angola', continent: 'Africa', area: 1246700 }),
  Map({ id: 31, name: 'Mali', continent: 'Africa', area: 1240000 }),
  Map({ id: 32, name: 'South Africa', continent: 'Africa', area: 1219912 }),
  Map({ id: 33, name: 'Colombia', continent: 'South America', area: 1138910 }),
  Map({ id: 34, name: 'Ethiopia', continent: 'Africa', area: 1127127 }),
  Map({ id: 35, name: 'Bolivia', continent: 'South America', area: 1098580 }),
  Map({ id: 36, name: 'Mauritania', continent: 'Africa', area: 1030700 }),
  Map({ id: 37, name: 'Egypt', continent: 'Africa', area: 1001450 }),
  Map({ id: 38, name: 'Tanzania', continent: 'Africa', area: 945087 }),
  Map({ id: 39, name: 'Nigeria', continent: 'Africa', area: 923768 }),
  Map({ id: 40, name: 'Venezuela', continent: 'South America', area: 912050 }),
  Map({ id: 41, name: 'Namibia', continent: 'Africa', area: 825418 }),
  Map({ id: 42, name: 'Pakistan', continent: 'Asia', area: 803940 }),
  Map({ id: 43, name: 'Mozambique', continent: 'Africa', area: 801590 }),
  Map({ id: 44, name: 'Turkey', continent: 'Asia', area: 780580 }),
  Map({ id: 45, name: 'Chile', continent: 'South America', area: 756950 }),
  Map({ id: 46, name: 'Zambia', continent: 'Africa', area: 752614 }),
  Map({ id: 47, name: 'Myanmar', continent: 'Asia', area: 678500 }),
  Map({ id: 48, name: 'Afghanistan', continent: 'Asia', area: 647500 }),
  Map({ id: 49, name: 'Somalia', continent: 'Africa', area: 637657 }),
  Map({ id: 50, name: 'Central African Republic', continent: 'Africa', area: 622984 }),
  Map({ id: 51, name: 'Ukraine', continent: 'Europe', area: 603700 }),
  Map({ id: 52, name: 'Botswana', continent: 'Africa', area: 600370 }),
  Map({ id: 53, name: 'Madagascar', continent: 'Africa', area: 587040 }),
  Map({ id: 54, name: 'Kenya', continent: 'Africa', area: 582650 }),
  Map({ id: 55, name: 'France', continent: 'Europe', area: 547030 }),
  Map({ id: 56, name: 'Yemen', continent: 'Asia', area: 527970 }),
  Map({ id: 57, name: 'Thailand', continent: 'Asia', area: 514000 }),
  Map({ id: 58, name: 'Spain', continent: 'Europe', area: 504782 }),
  Map({ id: 59, name: 'Turkmenistan', continent: 'Asia', area: 488100 }),
  Map({ id: 60, name: 'Cameroon', continent: 'Africa', area: 475440 }),
  Map({ id: 61, name: 'Papua New Guinea', continent: 'Australia', area: 462840 }),
  Map({ id: 62, name: 'Sweden', continent: 'Europe', area: 449964 }),
  Map({ id: 63, name: 'Uzbekistan', continent: 'Asia', area: 447400 }),
  Map({ id: 64, name: 'Morocco', continent: 'Africa', area: 446550 }),
  Map({ id: 65, name: 'Iraq', continent: 'Asia', area: 437072 }),
  Map({ id: 66, name: 'Paraguay', continent: 'Paraguay', area: 406750 }),
  Map({ id: 67, name: 'Zimbabwe', continent: 'Africa', area: 390580 }),
  Map({ id: 68, name: 'Japan', continent: 'Asia', area: 377835 }),
  Map({ id: 69, name: 'Germany', continent: 'Europe', area: 357021 }),
  Map({ id: 70, name: 'Congo, Republic of the', continent: 'Africa', area: 342000 }),
  Map({ id: 71, name: 'Finland', continent: 'Europe', area: 337030 }),
  Map({ id: 72, name: 'Malaysia', continent: 'Asia', area: 329750 }),
  Map({ id: 73, name: 'Vietnam', continent: 'Asia', area: 329560 }),
  Map({ id: 74, name: 'Norway', continent: 'Europe', area: 324220 }),
  Map({ id: 75, name: 'Côte d\'Ivoire', continent: 'Africa', area: 322460 }),
  Map({ id: 76, name: 'Poland', continent: 'Europe', area: 312685 }),
  Map({ id: 77, name: 'Italy', continent: 'Europe', area: 301230 }),
  Map({ id: 78, name: 'Philippines', continent: 'Asia', area: 300000 }),
  Map({ id: 79, name: 'Ecuador', continent: 'South America', area: 283560 }),
  Map({ id: 80, name: 'Burkina Faso', continent: 'Africa', area: 274200 }),
  Map({ id: 81, name: 'New Zealand', continent: 'Australia', area: 268680 }),
  Map({ id: 82, name: 'Gabon', continent: 'Africa', area: 267667 }),
  Map({ id: 83, name: 'Western Sahara', continent: 'Africa', area: 266000 }),
  Map({ id: 84, name: 'Guinea', continent: 'Africa', area: 245857 }),
  Map({ id: 85, name: 'United Kingdom', continent: 'Europe', area: 244820 }),
  Map({ id: 86, name: 'Ghana', continent: 'Africa', area: 239460 }),
  Map({ id: 87, name: 'Romania', continent: 'Europe', area: 237500 }),
  Map({ id: 88, name: 'Laos', continent: 'Asia', area: 236800 }),
  Map({ id: 89, name: 'Uganda', continent: 'Africa', area: 236040 }),
  Map({ id: 90, name: 'Guyana', continent: 'Africa', area: 214970 }),
  Map({ id: 91, name: 'Oman', continent: 'Asia', area: 309500 }),
  Map({ id: 92, name: 'Belarus', continent: 'Europe', area: 207600 }),
  Map({ id: 93, name: 'Kyrgyzstan', continent: 'Asia', area: 198500 }),
  Map({ id: 94, name: 'Senegal', continent: 'Africa', area: 196190 }),
  Map({ id: 95, name: 'Syria', continent: 'Asia', area: 185180 }),
  Map({ id: 96, name: 'Cambodia', continent: 'Africa', area: 181040 }),
  Map({ id: 97, name: 'Uruguay', continent: 'South America', area: 176220 }),
  Map({ id: 98, name: 'Tunisia', continent: 'Africa', area: 163610 }),
  Map({ id: 99, name: 'Suriname', continent: 'South America', area: 163270 }),
  Map({ id: 100, name: 'Bangladesh', continent: 'Asia', area: 144000 }),
  Map({ id: 101, name: 'Tajikistan', continent: 'Asia', area: 143100 }),
  Map({ id: 102, name: 'Nepal', continent: 'Asia', area: 140800 }),
  Map({ id: 103, name: 'Greece', continent: 'Europe', area: 131940 }),
  Map({ id: 104, name: 'Nicaragua', continent: 'Africa', area: 129494 }),
  Map({ id: 105, name: 'Eritrea', continent: 'Africa', area: 121320 }),
  Map({ id: 106, name: 'Korea, North', continent: 'Asia', area: 120540 }),
  Map({ id: 107, name: 'Malawi', continent: 'Africa', area: 118480 }),
  Map({ id: 108, name: 'Benin', continent: 'Africa', area: 112620 }),
  Map({ id: 109, name: 'Honduras', continent: 'North America', area: 112090 }),
  Map({ id: 110, name: 'Liberia', continent: 'Africa', area: 111370 }),
  Map({ id: 111, name: 'Bulgaria', continent: 'Europe', area: 110910 }),
  Map({ id: 112, name: 'Cuba', continent: 'North America', area: 110860 }),
  Map({ id: 113, name: 'Guatemala', continent: 'North America', area: 108890 }),
  Map({ id: 114, name: 'Iceland', continent: 'Europe', area: 103000 }),
  Map({ id: 115, name: 'Serbia and Montenegro', continent: 'Europe', area: 102350 }),
  Map({ id: 116, name: 'Korea, South', continent: 'Asia', area: 98480 }),
  Map({ id: 117, name: 'Hungary', continent: 'Europe', area: 93030 }),
  Map({ id: 118, name: 'Portugal', continent: 'Europe', area: 92391 }),
  Map({ id: 119, name: 'Jordan', continent: 'Asia', area: 92300 }),
  Map({ id: 120, name: 'French Guiana', continent: 'Africa', area: 91000 }),
  Map({ id: 121, name: 'Azerbaijan', continent: 'Asia', area: 86600 }),
  Map({ id: 122, name: 'Austria', continent: 'Europe', area: 83858 }),
  Map({ id: 123, name: 'United Arab Emirates', continent: 'Asia', area: 82880 }),
  Map({ id: 124, name: 'Czech Republic', continent: 'Europe', area: 78866 }),
  Map({ id: 125, name: 'Panama', continent: 'North America', area: 78200 }),
  Map({ id: 126, name: 'Sierra Leone', continent: 'Africa', area: 71740 }),
  Map({ id: 127, name: 'Ireland', continent: 'Europe', area: 70273 }),
  Map({ id: 128, name: 'Georgia', continent: 'Asia', area: 69700 }),
  Map({ id: 129, name: 'Sri Lanka', continent: 'Asia', area: 65610 }),
  Map({ id: 130, name: 'Lithuania', continent: 'Europe', area: 65200 }),
  Map({ id: 131, name: 'Latvia', continent: 'Europe', area: 64589 }),
  Map({ id: 132, name: 'Svalbard', continent: 'Europe', area: 62049 }),
  Map({ id: 133, name: 'Togo', continent: 'Africa', area: 56785 }),
  Map({ id: 134, name: 'Croatia', continent: 'Europe', area: 56542 }),
  Map({ id: 135, name: 'Bosnia and Herzegovina', continent: 'Europe', area: 51129 }),
  Map({ id: 136, name: 'Costa Rica', continent: 'North America', area: 51100 }),
  Map({ id: 137, name: 'Slovakia', continent: 'Europe', area: 48845 }),
  Map({ id: 138, name: 'Dominican Republic', continent: 'North America', area: 48730 }),
  Map({ id: 139, name: 'Bhutan', continent: 'Asia', area: 47000 }),
  Map({ id: 140, name: 'Estonia', continent: 'Europe', area: 45226 }),
  Map({ id: 141, name: 'Denmark', continent: 'Europe', area: 43094 }),
  Map({ id: 142, name: 'Netherlands', continent: 'Europe', area: 41526 }),
  Map({ id: 143, name: 'Switzerland', continent: 'Europe', area: 41290 }),
  Map({ id: 144, name: 'Guinea-Bissau', continent: 'Africa', area: 36120 }),
  Map({ id: 145, name: 'Republic of China (Taiwan)', continent: 'Asia', area: 35980 }),
  Map({ id: 146, name: 'Moldova', continent: 'Europe', area: 33843 }),
  Map({ id: 147, name: 'Belgium', continent: 'Europe', area: 30510 }),
  Map({ id: 148, name: 'Lesotho', continent: 'Africa', area: 30355 }),
  Map({ id: 149, name: 'Armenia', continent: 'Asia', area: 29800 }),
  Map({ id: 150, name: 'Albania', continent: 'Europe', area: 28748 }),
  Map({ id: 151, name: 'Solomon Islands', continent: 'Australia', area: 28450 }),
  Map({ id: 152, name: 'Equatorial Guinea', continent: 'Africa', area: 28051 }),
  Map({ id: 153, name: 'Burundi', continent: 'Africa', area: 27830 }),
  Map({ id: 154, name: 'Haiti', continent: 'Africa', area: 27750 }),
  Map({ id: 156, name: 'Republic of Macedonia', continent: 'Europe', area: 25333 }),
  Map({ id: 157, name: 'Djibouti', continent: 'Africa', area: 23000 }),
  Map({ id: 158, name: 'Belize', continent: 'North America', area: 22966 }),
  Map({ id: 159, name: 'El Salvador', continent: 'North America', area: 21040 }),
  Map({ id: 160, name: 'Israel', continent: 'Asia', area: 20770 }),
  Map({ id: 161, name: 'Slovenia', continent: 'Europe', area: 20273 }),
  Map({ id: 162, name: 'New Caledonia', continent: 'Australia', area: 19060 }),
  Map({ id: 163, name: 'Fiji', continent: 'Australia', area: 18270 }),
  Map({ id: 164, name: 'Kuwait', continent: 'Asia', area: 17820 }),
  Map({ id: 165, name: 'Swaziland', continent: 'Africa', area: 17363 }),
  Map({ id: 166, name: 'East Timor', continent: 'Asia', area: 15007 }),
  Map({ id: 167, name: 'Bahamas', continent: 'North America', area: 13940 }),
  Map({ id: 168, name: 'Vanuatu', continent: 'Australia', area: 12200 }),
  Map({ id: 169, name: 'Falkland Islands (Islas Malvinas)', continent: 'South America', area: 12173 }),
  Map({ id: 170, name: 'Nagorno-Karabakh Republic', continent: 'Asia', area: 12170 }),
  Map({ id: 171, name: 'Qatar', continent: 'Asia', area: 11437 }),
  Map({ id: 172, name: 'Gambia, The', continent: 'Africa', area: 11300 }),
  Map({ id: 173, name: 'Jamaica', continent: 'North America', area: 10991 }),
  Map({ id: 174, name: 'Lebanon', continent: 'Asia', area: 10452 }),
  Map({ id: 175, name: 'Cyprus', continent: 'Asia', area: 9250 }),
  Map({ id: 176, name: 'Puerto Rico', continent: 'North America', area: 9104 }),
  Map({ id: 177, name: 'French Southern and Antarctic Lands', continent: 'Antarctica', area: 7829 }),
  Map({ id: 178, name: 'West Bank', continent: 'Asia', area: 5860 }),
  Map({ id: 179, name: 'Brunei', continent: 'Asia', area: 5770 }),
  Map({ id: 180, name: 'Trinidad and Tobago', continent: 'North America', area: 5128 }),
  Map({ id: 181, name: 'French Polynesia', continent: 'Australia', area: 4167 }),
  Map({ id: 182, name: 'Cape Verde', continent: 'Africa', area: 4033 }),
  Map({ id: 183, name: 'South Georgia and the South Sandwich Islands', continent: 'Antarctica', area: 3903 }),
  Map({ id: 184, name: 'Samoa', continent: 'Australia', area: 2944 }),
  Map({ id: 185, name: 'Luxembourg', continent: 'Europe', area: 2586 }),
  Map({ id: 186, name: 'Réunion', continent: 'Africa', area: 2517 }),
  Map({ id: 187, name: 'Comoros', continent: 'Africa', area: 2170 }),
  Map({ id: 188, name: 'Mauritius', continent: 'Africa', area: 2040 }),
  Map({ id: 189, name: 'Guadeloupe', continent: 'North America', area: 1780 }),
  Map({ id: 190, name: 'Faroe Islands', continent: 'Europe', area: 1399 }),
  Map({ id: 191, name: 'Martinique', continent: 'North America', area: 1100 }),
  Map({ id: 192, name: 'Hong Kong', continent: 'Asia', area: 1092 }),
  Map({ id: 193, name: 'São Tomé and Príncipe', continent: 'Africa', area: 1001 }),
  Map({ id: 194, name: 'Netherlands Antilles', continent: 'Europe', area: 960 }),
  Map({ id: 195, name: 'Kiribati', continent: 'Australia', area: 811 }),
  Map({ id: 196, name: 'Dominica', continent: 'North America', area: 754 }),
  Map({ id: 197, name: 'Tonga', continent: 'Africa', area: 748 }),
  Map({ id: 198, name: 'Micronesia, Federated States of', continent: 'Australia', area: 702 }),
  Map({ id: 199, name: 'Singapore', continent: 'Asia', area: 693 }),
  Map({ id: 200, name: 'Bahrain', continent: 'Asia', area: 665 }),
  Map({ id: 201, name: 'Saint Lucia', continent: 'North America', area: 616 }),
  Map({ id: 202, name: 'Isle of Man', continent: 'Europe', area: 572 }),
  Map({ id: 203, name: 'Guam', continent: 'Australia', area: 549 }),
  Map({ id: 204, name: 'Northern Mariana Islands', continent: 'Australia', area: 477 }),
  Map({ id: 205, name: 'Andorra', continent: 'Europe', area: 468 }),
  Map({ id: 206, name: 'Palau', continent: 'Australia', area: 458 }),
  Map({ id: 207, name: 'Seychelles', continent: 'Africa', area: 455 }),
  Map({ id: 208, name: 'Antigua and Barbuda', continent: 'North America', area: 443 }),
  Map({ id: 209, name: 'Barbados', continent: 'North America', area: 431 }),
  Map({ id: 210, name: 'Turks and Caicos Islands', continent: 'North America', area: 430 }),
  Map({ id: 211, name: 'Heard Island and McDonald Islands', continent: 'Antarctica', area: 412 }),
  Map({ id: 212, name: 'Saint Helena (Britain)', continent: 'Africa', area: 410 }),
  Map({ id: 213, name: 'Saint Vincent and the Grenadines', continent: 'North America', area: 389 }),
  Map({ id: 214, name: 'Mayotte', continent: 'Africa', area: 374 }),
  Map({ id: 215, name: 'Jan Mayen', continent: 'Europe', area: 373 }),
  Map({ id: 216, name: 'Gaza Strip', continent: 'Asia', area: 360 }),
  Map({ id: 217, name: 'Virgin Islands', continent: 'North America', area: 352 }),
  Map({ id: 218, name: 'Grenada', continent: 'North America', area: 344 }),
  Map({ id: 219, name: 'Malta', continent: 'Europe', area: 316 }),
  Map({ id: 220, name: 'Maldives', continent: 'Asia', area: 300 }),
  Map({ id: 221, name: 'Wallis and Futuna', continent: 'Australia', area: 274 }),
  Map({ id: 222, name: 'Cayman Islands', continent: 'North America', area: 262 }),
  Map({ id: 223, name: 'Saint Kitts and Nevis', continent: 'North America', area: 261 }),
  Map({ id: 224, name: 'Niue', continent: 'Australia', area: 260 }),
  Map({ id: 225, name: 'Saint Pierre and Miquelon', continent: 'North America', area: 242 }),
  Map({ id: 226, name: 'Cook Islands', continent: 'Australia', area: 240 }),
  Map({ id: 227, name: 'American Samoa', continent: 'Australia', area: 199 }),
  Map({ id: 228, name: 'Aruba', continent: 'North America', area: 193 }),
  Map({ id: 229, name: 'Marshall Islands', continent: 'Australia', area: 181 }),
  Map({ id: 230, name: 'Liechtenstein', continent: 'Europe', area: 160 }),
  Map({ id: 231, name: 'British Virgin Islands', continent: 'North America', area: 153 }),
  Map({ id: 232, name: 'Christmas Island', continent: 'Asia', area: 135 }),
  Map({ id: 233, name: 'Jersey', continent: 'Europe', area: 116 }),
  Map({ id: 234, name: 'Anguilla', continent: 'North America', area: 102 }),
  Map({ id: 235, name: 'Montserrat', continent: 'North America', area: 102 }),
  Map({ id: 236, name: 'Guernsey', continent: 'Europe', area: 78 }),
  Map({ id: 237, name: 'San Marino', continent: 'Europe', area: 61 }),
  Map({ id: 238, name: 'British Indian Ocean Territory', continent: 'Asia', area: 60 }),
  Map({ id: 239, name: 'Bouvet Island', continent: 'Antarctica', area: 59 }),
  Map({ id: 240, name: 'Bermuda', continent: 'North America', area: 53 }),
  Map({ id: 241, name: 'Pitcairn Islands', continent: 'Australia', area: 47 }),
  Map({ id: 242, name: 'Norfolk Island', continent: 'Australia', area: 35 }),
  Map({ id: 243, name: 'Europa Island', continent: 'Africa', area: 28 }),
  Map({ id: 244, name: 'Tuvalu', continent: 'Australia', area: 26 }),
  Map({ id: 245, name: 'Macau', continent: 'Asia', area: 25 }),
  Map({ id: 246, name: 'Nauru', continent: 'Australia', area: 21 }),
  Map({ id: 247, name: 'Cocos (Keeling) Islands', continent: 'Asia', area: 14 }),
  Map({ id: 248, name: 'Palmyra Atoll', continent: 'Australia', area: 12 }),
  Map({ id: 249, name: 'Tokelau', continent: 'Australia', area: 10 }),
  Map({ id: 250, name: 'Gibraltar', continent: 'Europe', area: 7 }),
  Map({ id: 251, name: 'Wake Island', continent: 'Australia', area: 7 }),
  Map({ id: 252, name: 'Midway Atoll', continent: 'Australia', area: 6 }),
  Map({ id: 253, name: 'Clipperton Island', continent: 'North America', area: 6 }),
  Map({ id: 254, name: 'Navassa Island', continent: 'North America', area: 5 }),
  Map({ id: 255, name: 'Ashmore and Cartier Islands', continent: 'Australia', area: 5 }),
  Map({ id: 256, name: 'Glorioso Islands', continent: 'Africa', area: 5 }),
  Map({ id: 257, name: 'Spratly Islands', continent: 'Asia', area: 5 }),
  Map({ id: 258, name: 'Jarvis Island', continent: 'Australia', area: 5 }),
  Map({ id: 259, name: 'Juan de Nova Island', continent: 'Africa', area: 4 }),
  Map({ id: 260, name: 'Coral Sea Islands', continent: 'Australia', area: 3 }),
  Map({ id: 261, name: 'Johnston Atoll', continent: 'North America', area: 3 }),
  Map({ id: 262, name: 'Monaco', continent: 'Europe', area: 2 }),
  Map({ id: 263, name: 'Howland Island', continent: 'Australia', area: 2 }),
  Map({ id: 264, name: 'Baker Island', continent: 'Australia', area: 1 }),
  Map({ id: 265, name: 'Kingman Reef', continent: 'Australia', area: 1 }),
  Map({ id: 266, name: 'Tromelin Island', continent: 'Africa', area: 1 }),
  Map({ id: 267, name: 'Holy See (Vatican City)', continent: 'Europe', area: 0.44 }),
]);